name: CI
on: [ pull_request, workflow_dispatch ]
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: mvn verify -PcheckFormat -B
    - name: Publish Unit Test Results
      id: publish
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/target/surefire-reports/*.xml'
        comment_mode: off
